import type { Catalog, LessonDefinition } from "@abl/block-schema";
import { createLessonGuide, lessonLevelLabel } from "./lessonGuide";

export type UnitLessonSummary = {
  id: string;
  title: string;
  level: string;
  minutes: number;
  partCount: number;
  wiringCount: number;
  blockCount: number;
  materials: string[];
  concepts: string[];
  libraries: string[];
  teacherNotes: string[];
};

export type TeacherUnitPlan = {
  title: string;
  totalLessons: number;
  totalMinutes: number;
  sessionMinutes: number;
  sessionCount: number;
  totalParts: number;
  totalWires: number;
  totalBlocks: number;
  materials: string[];
  concepts: string[];
  libraries: string[];
  prepNotes: string[];
  lessons: UnitLessonSummary[];
};

export type UnitPlanOptions = {
  title?: string;
  sessionMinutes?: number;
};

function unique(values: string[]) {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean)));
}

function safeFilename(value: string) {
  return value.replace(/[^a-zA-Z0-9_-]/g, "_");
}

function plural(count: number, noun: string) {
  return `${count} ${noun}${count === 1 ? "" : "s"}`;
}

export function unitPlanFilename(plan: TeacherUnitPlan) {
  return `${safeFilename(plan.title)}-unit-plan.md`;
}

export function createUnitPlan(lessons: LessonDefinition[], catalog: Catalog, options: UnitPlanOptions = {}): TeacherUnitPlan {
  const sessionMinutes = options.sessionMinutes ?? 45;
  const lessonSummaries = lessons.map((lesson) => {
    const guide = createLessonGuide(lesson, catalog);
    return {
      id: lesson.id,
      title: lesson.title,
      level: lessonLevelLabel(lesson.level),
      minutes: guide.minutes,
      partCount: guide.partCount,
      wiringCount: guide.wiringCount,
      blockCount: guide.blockCount,
      materials: guide.materials,
      concepts: guide.concepts,
      libraries: guide.libraries,
      teacherNotes: guide.teacherNotes
    };
  });
  const totalMinutes = lessonSummaries.reduce((total, lesson) => total + lesson.minutes, 0);
  const totalWires = lessonSummaries.reduce((total, lesson) => total + lesson.wiringCount, 0);
  const totalBlocks = lessonSummaries.reduce((total, lesson) => total + lesson.blockCount, 0);
  const libraries = unique(lessonSummaries.flatMap((lesson) => lesson.libraries));
  const teacherNotes = unique(lessonSummaries.flatMap((lesson) => lesson.teacherNotes));
  const prepNotes = [
    totalWires > 0 ? `Prepare jumper wires and breadboards for ${totalWires} planned wire checks across the path.` : "",
    libraries.length > 0 ? `Install or queue Arduino libraries before class: ${libraries.join(", ")}.` : "",
    ...teacherNotes
  ];

  return {
    title: options.title ?? "Arduino Blocks Lab Starter Unit",
    totalLessons: lessonSummaries.length,
    totalMinutes,
    sessionMinutes,
    sessionCount: totalMinutes === 0 ? 0 : Math.ceil(totalMinutes / sessionMinutes),
    totalParts: lessonSummaries.reduce((total, lesson) => total + lesson.partCount, 0),
    totalWires,
    totalBlocks,
    materials: unique(lessonSummaries.flatMap((lesson) => lesson.materials)),
    concepts: unique(lessonSummaries.flatMap((lesson) => lesson.concepts)),
    libraries,
    prepNotes: unique(prepNotes),
    lessons: lessonSummaries
  };
}

function linesForList(values: string[], empty: string) {
  return values.length > 0 ? values.map((value) => `- ${value}`) : [`- ${empty}`];
}

export function createUnitPlanMarkdown(plan: TeacherUnitPlan) {
  const lines = [
    `# ${plan.title}`,
    "",
    "Generated by Arduino Blocks Lab.",
    "",
    "## Pacing",
    `- Lessons: ${plan.totalLessons}`,
    `- Total time: ${plan.totalMinutes} minutes`,
    `- Suggested sessions: ${plan.sessionCount} x ${plan.sessionMinutes} minute class periods`,
    `- Build load: ${plural(plan.totalParts, "part")}, ${plural(plan.totalWires, "wire")}, ${plural(plan.totalBlocks, "block")}`,
    "",
    "## Materials",
    ...linesForList(plan.materials, "No materials yet."),
    "",
    "## Concepts",
    ...linesForList(plan.concepts, "No concepts yet."),
    "",
    "## Libraries",
    ...linesForList(plan.libraries, "No external libraries."),
    "",
    "## Teacher Prep",
    ...linesForList(plan.prepNotes, "No special prep notes."),
    "",
    "## Lesson Path"
  ];

  for (const [index, lesson] of plan.lessons.entries()) {
    lines.push(
      "",
      `### ${index + 1}. ${lesson.title}`,
      `- Level: ${lesson.level}`,
      `- Time: ${lesson.minutes} minutes`,
      `- Build: ${plural(lesson.partCount, "part")}, ${plural(lesson.wiringCount, "wire")}, ${plural(lesson.blockCount, "block")}`,
      `- Concepts: ${lesson.concepts.length > 0 ? lesson.concepts.join(", ") : "none listed"}`,
      `- Materials: ${lesson.materials.length > 0 ? lesson.materials.join(", ") : "none listed"}`
    );
  }

  return `${lines.join("\n")}\n`;
}
